//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAndLoadTestProject1
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class WebTest1Coded : WebTest
    {

        public WebTest1Coded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request1.ExpectedResponseUrl = "https://api.bing.com/qsml.aspx?query=n&maxwidth=32765&rowheight=20&sectionHeight=" +
                "160&FORM=IESS4A&market=en-US";
            request1.QueryStringParameters.Add("query", "n", false, false);
            request1.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request1.QueryStringParameters.Add("rowheight", "20", false, false);
            request1.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request1.QueryStringParameters.Add("FORM", "IESS4A", false, false);
            request1.QueryStringParameters.Add("market", "en-US", false, false);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request2.ExpectedResponseUrl = "https://api.bing.com/qsml.aspx?query=nU&maxwidth=32765&rowheight=20&sectionHeight" +
                "=160&FORM=IESS4A&market=en-US";
            request2.QueryStringParameters.Add("query", "nU", false, false);
            request2.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request2.QueryStringParameters.Add("rowheight", "20", false, false);
            request2.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request2.QueryStringParameters.Add("FORM", "IESS4A", false, false);
            request2.QueryStringParameters.Add("market", "en-US", false, false);
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request3.ExpectedResponseUrl = "https://api.bing.com/qsml.aspx?query=nUE&maxwidth=32765&rowheight=20&sectionHeigh" +
                "t=160&FORM=IESS4A&market=en-US";
            request3.QueryStringParameters.Add("query", "nUE", false, false);
            request3.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request3.QueryStringParameters.Add("rowheight", "20", false, false);
            request3.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request3.QueryStringParameters.Add("FORM", "IESS4A", false, false);
            request3.QueryStringParameters.Add("market", "en-US", false, false);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request4.ExpectedResponseUrl = "https://api.bing.com/qsml.aspx?query=nUEV&maxwidth=32765&rowheight=20&sectionHeig" +
                "ht=160&FORM=IESS4A&market=en-US";
            request4.QueryStringParameters.Add("query", "nUEV", false, false);
            request4.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request4.QueryStringParameters.Add("rowheight", "20", false, false);
            request4.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request4.QueryStringParameters.Add("FORM", "IESS4A", false, false);
            request4.QueryStringParameters.Add("market", "en-US", false, false);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request5.ExpectedResponseUrl = "https://api.bing.com/qsml.aspx?query=nUEVO&maxwidth=32765&rowheight=20&sectionHei" +
                "ght=160&FORM=IESS4A&market=en-US";
            request5.QueryStringParameters.Add("query", "nUEVO", false, false);
            request5.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request5.QueryStringParameters.Add("rowheight", "20", false, false);
            request5.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request5.QueryStringParameters.Add("FORM", "IESS4A", false, false);
            request5.QueryStringParameters.Add("market", "en-US", false, false);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://www.bing.com/search");
            request6.ExpectedResponseUrl = "https://www.bing.com/search?q=nUEVO&src=IE-SearchBox&FORM=IESR4A";
            request6.QueryStringParameters.Add("q", "nUEVO", false, false);
            request6.QueryStringParameters.Add("src", "IE-SearchBox", false, false);
            request6.QueryStringParameters.Add("FORM", "IESR4A", false, false);
            ExtractHiddenFields extractionRule1 = new ExtractHiddenFields();
            extractionRule1.Required = true;
            extractionRule1.HtmlDecode = true;
            extractionRule1.ContextParameterName = "1";
            request6.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule1.Extract);
            ExtractText extractionRule2 = new ExtractText();
            extractionRule2.StartsWith = "&amp;IG=";
            extractionRule2.EndsWith = "&";
            extractionRule2.Index = 0;
            extractionRule2.IgnoreCase = false;
            extractionRule2.UseRegularExpression = false;
            extractionRule2.HtmlDecode = true;
            extractionRule2.Required = false;
            extractionRule2.ContextParameterName = "QueryStringParam23.IG";
            request6.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule2.Extract);
            ExtractText extractionRule3 = new ExtractText();
            extractionRule3.StartsWith = "\\u0026ct=";
            extractionRule3.EndsWith = "\\";
            extractionRule3.Index = 0;
            extractionRule3.IgnoreCase = false;
            extractionRule3.UseRegularExpression = false;
            extractionRule3.HtmlDecode = true;
            extractionRule3.Required = false;
            extractionRule3.ContextParameterName = "QueryStringParam34.ct";
            request6.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule3.Extract);
            ExtractText extractionRule4 = new ExtractText();
            extractionRule4.StartsWith = "\\u0026wreply=";
            extractionRule4.EndsWith = "\\";
            extractionRule4.Index = 0;
            extractionRule4.IgnoreCase = false;
            extractionRule4.UseRegularExpression = false;
            extractionRule4.HtmlDecode = true;
            extractionRule4.Required = false;
            extractionRule4.ContextParameterName = "QueryStringParam37.wreply";
            request6.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule4.Extract);
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("https://www.bing.com/fd/ls/l");
            request7.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            request7.QueryStringParameters.Add("IG", this.Context["QueryStringParam23.IG"].ToString(), false, false);
            request7.QueryStringParameters.Add("Type", "Event.CPT", false, false);
            request7.QueryStringParameters.Add("DATA", "{%22pp%22:{%22S%22:%22L%22,%22FC%22:108,%22BC%22:168,%22SE%22:-1,%22TC%22:-1,%22H" +
                    "%22:200,%22BP%22:397,%22CT%22:404,%22IL%22:2},%22ad%22:[-1,-1,1161,782,1161,1444" +
                    ",68]}", false, false);
            request7.QueryStringParameters.Add("P", "SERP", false, false);
            request7.QueryStringParameters.Add("DA", "HK2", false, false);
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("https://www.bing.com/fd/ls/lsp.aspx");
            request8.Method = "POST";
            request8.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            request8.QueryStringParameters.Add("", "", false, false);
            StringHttpBody request8Body = new StringHttpBody();
            request8Body.ContentType = "text/xml";
            request8Body.InsertByteOrderMark = false;
            request8Body.BodyString = @"<ClientInstRequest><Events><E><T>Event.ClientInst</T><IG>DC7BE9FB0FBE4E39A3D23C75EA5FDACC</IG><TS>1519827954875</TS><D><![CDATA[{id:1230,P:""7:ee,5:ee,15:qi,14:nv,13:nv,12:nv,11:eg,4:ee,3:ee,2:ee,17:ta,16:t9,24:jt,8:ef,10:n2,9:eg"",S:""nav:0"",v:1.1,T:""CI.Perf"",FID:""CI"",Name:""PerfV2""}]]></D></E></Events><STS>1519827954875</STS></ClientInstRequest>";
            request8.Body = request8Body;
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("https://www.bing.com/work/api/v2/user/discover");
            request9.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            request9.QueryStringParameters.Add("update", "true", false, false);
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("https://login.live.com/login.srf");
            request10.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            request10.QueryStringParameters.Add("wa", "wsignin1.0", false, false);
            request10.QueryStringParameters.Add("rpsnv", "11", false, false);
            request10.QueryStringParameters.Add("ct", this.Context["QueryStringParam34.ct"].ToString(), false, false);
            request10.QueryStringParameters.Add("rver", "6.0.5286.0", false, false);
            request10.QueryStringParameters.Add("wp", "MBI", false, false);
            request10.QueryStringParameters.Add("wreply", this.Context["QueryStringParam37.wreply"].ToString(), false, false);
            request10.QueryStringParameters.Add("lc", "4096", false, false);
            request10.QueryStringParameters.Add("id", "264960", false, false);
            request10.QueryStringParameters.Add("checkda", "1", false, false);
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("https://www.bing.com/secure/Passport.aspx");
            request11.Method = "POST";
            request11.Headers.Add(new WebTestRequestHeader("Referer", "https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=11&ct=1519828062&rver=6.0.52" +
                        "86.0&wp=MBI&wreply=https:%2F%2fwww.bing.com%2Fsecure%2FPassport.aspx%3Fpopup%3D1" +
                        "%26ssl%3D1&lc=4096&id=264960&checkda=1"));
            request11.QueryStringParameters.Add("popup", "1", false, false);
            request11.QueryStringParameters.Add("ssl", "1", false, false);
            request11.QueryStringParameters.Add("wa", "wsignin1.0", false, false);
            FormPostHttpBody request11Body = new FormPostHttpBody();
            request11Body.FormPostParameters.Add("NAPExp", "Fri, 08-Jun-2018 21:27:44 GMT");
            request11Body.FormPostParameters.Add("NAP", "V%3D1.9%26E%3D148e%26C%3DZiVtgI3OT-kJgcxHBDwRRy0o-NQGRqjL6CqLQijPHRbLKopsb80q6w%2" +
                    "6W%3D2");
            request11Body.FormPostParameters.Add("ANON", "A%3D03E90F525E8D02BE1DC663A1FFFFFFFF%26E%3D14e8%26W%3D2");
            request11Body.FormPostParameters.Add("ANONExp", "Sun, 16-Sep-2018 21:27:44 GMT");
            request11Body.FormPostParameters.Add("t", @"EgAqAgMAAAAEgAAADAABIi+eg+zRxA/DkX69VttiC1IIXhe5z5tWUHyHw8Jp5B5O3YDQlWyXfOH7u6WJDi+z9421IcNsIV6T2rdtb55gik8xe6RNNHP8qtCQP3HOtzHBXdwoRNoOn+xuzXudUsj/gMELCLb6d+OpzRVMleyhqByF5vQJcFo3YwYthGVa6mriWJeQ0G9K9T1c/QWRNICdc4FZo946gCKgqbu10OBKwE4qwTzVNacxf21LVGVaXoKlE+kAMoMy0gljIQ7KTvXXmIkc3RMlAQW5nrlXEOIHXizyvb/a8wBOhhoMiiAQtKAqyzOlv1Val8zF1iExYKVj6DKtYjkuqPv/ImMB5fEj2hkBeAAZAQAAAwCppzb/XryWWjm4lloACwQAABMAABAUAGRtb3JhbGVzQGNybm92YS5jb20AYQAAIGRtb3JhbGVzJWNybm92YS5jb21AcGFzc3BvcnQuY29tAAAABENSAAAAAAAABAkAAAAAAFVAIAZBAAZEYW5pZWwADU1vcmFsZXMgQmVpdGEAAAAAAAAAAAAAAAAAAAAAAADAjrRXkI0EsgAAXryWWt4sl1oAAAAAAAAAAAAAAAAPADE5MC4yNDEuMTgzLjE4AAUBAAAAAUAYAMRr+5YAAQQAAAAAAAAAAAAAAAAAAAAryd09fAX4Av+/GABV8meR/78YAFPyZ5EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");
            request11.Body = request11Body;
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("https://www.bing.com/fd/ls/lsp.aspx");
            request12.ThinkTime = 1;
            request12.Method = "POST";
            request12.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            StringHttpBody request12Body = new StringHttpBody();
            request12Body.ContentType = "text/xml";
            request12Body.InsertByteOrderMark = false;
            request12Body.BodyString = "<ClientInstRequest><Events><E><T>Event.ClientInst</T><IG>DC7BE9FB0FBE4E39A3D23C75" +
                "EA5FDACC</IG><TS>1519827957101</TS><D><![CDATA[[{\"T\":\"CI.BoxModel\",\"FID\":\"CI\",\"N" +
                "ame\":\"v2.8\",\"SV\":\"4\",\"P\":{\"C\":94,\"N\":1,\"I\":\"2kh\",\"S\":\"T+C+BD\",\"M\":\"V+L+M+MT+E+N+" +
                "C+K+BD\",\"T\":3467,\"K\":\"SPAN.ftrB+LI.b_algo+LI.b_ans+144+SERP,5021.1+2mx+www.bing." +
                "com+img+https+10t+10k+18w+1a5+1ar+1ax+1b8+1bp+1ch+1dk+1e0+1el+1fa+Framework+scri" +
                "pt+1fh+Identity%2520Blue%24BlueIdentityDropdownBootStrap_Redirect+1gu+Identity%2" +
                "520Blue%24BlueIdentityHeader+1gx+Identity%2520SnrWindowsLiveConnectBootstrap+1h2" +
                "+LanguageSwitch+1h6+SegmentFilters%2520Blue%24GenericDropDownModernCalendar+1j8+" +
                "BingAtWork%2520UserDiscovery+1l2+xmlhttprequest+1n5+WebResult%2520Blue%24WebResu" +
                "ltToolboxBlue+1le+VisualSystem%2520Footer%24IPv6TestScript+1mm+Web%2520SerpKeybo" +
                "ardNavigation_SelectorHeaderPlusAlgo+1mw+Web%2520SerpKeyboardNavigation+1mz+1v3+" +
                "pointermove\",\"F\":0},\"V\":\"l8/0/0/wq/lq/w9/3b/1/d/visible/default+np//////@3////\"," +
                "\"L\":\"l9/0/NAV.b_scopebar/SERP,5016.1/2s/27/th/13/2/T/-1+l9/1/H1.b_logo//1m/g/s/1" +
                "0/4/T/-1+l9/2/DIV.b_searchboxForm//2s/e/fk/14/3/T/-1+l9/3/DIV#id_h/@4/0/0/0/0/2/" +
                "T/2+ns/4/SPAN.sb_count//3c/3o/3k/u/3/T/-1+ns/5/@0/SERP,5250.1/6w/3o/2q/u/3/T/-1+" +
                "ns/6/@0/SERP,5258.1/9n/3o/3i/u/3/T/-1+ns/7/@0/SERP,5262.1/d5/3o/2e/u/3/T/-1+ns/8" +
                "/@1/SERP,5098.1/2s/4i/fk/2r/3/T/-1+ns/9/@1/SERP,5110.1/2s/7b/fk/28/3/T/-1+ns/a/@" +
                "1/SERP,5121.1/2s/9l/fk/2p/3/T/-1+ns/b/@1/SERP,5133.1/2s/cc/fk/28/3/T/-1+ns/c/@1/" +
                "SERP,5146.1/2s/em/fk/2p/3/T/-1+ns/d/@1/SERP,5159.1/2s/hd/fk/2p/3/T/-1+ns/e/@1/SE" +
                "RP,5171.1/2s/k4/fk/2p/3/T/-1+ns/f/@1/SERP,5183.1/2s/mv/fk/2p/3/T/-1+ns/g/@1/SERP" +
                ",5196.1/2s/pm/fk/36/3/T/-1+ns/h/@1/SERP,5208.1/2s/su/fk/2p/3/T/-1+ns/i/@2/SERP,5" +
                "292.1/2s/vl/fk/55/3/T/-1+ns/j/LI.b_pag/SERP,5312.1/2s/10s/fk/2q/3/T/-1+ns/k/@2/S" +
                "ERP,5302.1/jg/4i/ao/5l/3/T/-1+ns/l/FOOTER#b_footer/SERP,5035.1/0/@3/w9/1c/1/T/-1" +
                "+l9/m/IMG//1m/g/jb/1q/5/T/-1+l9/n/IMG#id_p/@4/0/0/0/0/4/T/2+@5/3///r0/a/45/1e//R" +
                "/+@5/n///sh/j/w/w//R/\",\"N\":\"-1/0///document//ta//ee/-1/ee/ef/eg/n2+jo/1/m/@6/sim" +
                "g%2FSharedSpriteDesktopTwoToneLogoTealSpy_0817.png/@7/z/@8/kk/-1/kk/kk/kk/kn+yi/" +
                "2//@6/cpt/@7/29/@8/yk/-1/yk/yk/-1/10r+yy/3//@6/ls%2Flsp.aspx/@11/o5/@8/@9/-1/@9/" +
                "119/1n3/1n4+z1/4//@6/BingCore.Bundle/@n/1j/@8/@a/-1/@a/@a/@a/10l+17k/5//@6/@m/@7" +
                "/2e/@8/@b/-1/@b/@b/@b/19z+1a0/6//@6/@p/@7/5/@8/@c/-1/@c/@c/@c/@c+1a7/7//@6/@r/@7" +
                "/k/@8/@d/-1/@d/@d/@d/1as+1at/8//@6/@t/@7/4/@8/@e/-1/@e/@e/@e/1ay+1az/9//@6/@v/@7" +
                "/9/@8/@f/-1/@f/@f/@f/@f+1b9/a//@6/@x/@7/g/@8/@g/-1/@g/@g/@g/1bq+1br/b//@6/@z/@7/" +
                "q/@8/@h/-1/@h/@h/@h/1ci+1cj/c//@6/@13/@7/11/@8/@i/-1/@i/@i/@i/1dl+1dm/d//@6/@15/" +
                "@7/e/@8/@j/-1/@j/@j/@j/1e1+1e2/e//@6/@17/@7/j/@8/@k/-1/@k/@k/@k/1em+1eo/f//@6/@1" +
                "9/@7/n/@8/@l/-1/@l/@l/@l/1fb+1fd/g//@6/@m/@n/5/@8/@o/-1/@o/@o/@o/1fi+1gr/h//@6/@" +
                "p/@n/2/@8/@q/-1/@q/@q/@q/@q+1gv/i//@6/@r/@n/2/@8/@s/-1/@s/@s/@s/1gy+1h0/j//@6/@t" +
                "/@n/2/@8/@u/-1/@u/@u/@u/@u+1h3/k//@6/@v/@n/2/@8/@w/-1/@w/@w/@w/@w+1j5/l//@6/@x/@" +
                "n/3/@8/@y/-1/@y/@y/@y/@y+1kz/m//@6/@z/@n/3/@8/@10/-1/@10/@10/@10/1l3+1l6/n//@6/u" +
                "ser%2Fdiscover/@11/3d/@8/@12/-1/@12/@12/1oi/1ok+1l8/o//@6/@13/@n/6/@8/@14/-1/@14" +
                "/@14/@14/1lf+1mj/p//@6/@15/@n/3/@8/@16/-1/@16/@16/@16/@16+1mu/q//@6/@17/@n/2/@8/" +
                "@18/-1/@18/@18/@18/@18+1my/r//@6/@19/@n/1/@8/@1a/-1/@1a/@1a/@1a/1n0+1qc/s//login" +
                ".live.com/login.srf/subdocument/dq/@8/-1/-1/-1/-1/-1/242+2eo/t//storage.live.com" +
                "/profilephoto%3AUserTileStatic%2Fp/@7/0/@8/-1/-1/-1/-1/-1/-1\",\"C\":\"@1b//@1c/mous" +
                "e/-1/0/34/0+1vj/////f/30/+1vr/////q/2z/+1vz/////10/2x/+1w7/////1j/2v/+1wf/////26" +
                "/2s/+1wn/0////2u/2o/+1ww/////3c/2l/+1x3/////3y/2k/+1xc/////4k/2f/+1xl/////4x/2e/" +
                "+1xv/////5a/2d/+1y1/////5o/2a/+1y8/////5y/29/+1yf/////68/27/+1yn/////6k/24/+1yv/" +
                "////6v/23/+1z3/////76/20/+1zj/////7n/1y/+1zz/////83/1v/+20f/////8f/1t/+213/////8" +
                "q/1s/+21r/////8v/1r/\",\"BD\":\"@1b/@1c/1519827956\"}]]]></D></E></Events><STS>151982" +
                "7957101</STS></ClientInstRequest>";
            request12.Body = request12Body;
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("https://www2.bing.com/ipv6test/test");
            request13.ThinkTime = 3;
            request13.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("https://www.bing.com/AS/Suggestions");
            request14.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            request14.QueryStringParameters.Add("pt", "page.serp", false, false);
            request14.QueryStringParameters.Add("bq", "nUEVO", false, false);
            request14.QueryStringParameters.Add("mkt", "es-cr", false, false);
            request14.QueryStringParameters.Add("qry", "go", false, false);
            request14.QueryStringParameters.Add("cp", "0", false, false);
            request14.QueryStringParameters.Add("css", "1", false, false);
            request14.QueryStringParameters.Add("cvid", "DC7BE9FB0FBE4E39A3D23C75EA5FDACC", false, false);
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("https://www.bing.com/AS/Suggestions");
            request15.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            request15.QueryStringParameters.Add("pt", "page.serp", false, false);
            request15.QueryStringParameters.Add("bq", "nUEVO", false, false);
            request15.QueryStringParameters.Add("mkt", "es-cr", false, false);
            request15.QueryStringParameters.Add("qry", "goo", false, false);
            request15.QueryStringParameters.Add("cp", "0", false, false);
            request15.QueryStringParameters.Add("cvid", "DC7BE9FB0FBE4E39A3D23C75EA5FDACC", false, false);
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("https://www.bing.com/AS/Suggestions");
            request16.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            request16.QueryStringParameters.Add("pt", "page.serp", false, false);
            request16.QueryStringParameters.Add("bq", "nUEVO", false, false);
            request16.QueryStringParameters.Add("mkt", "es-cr", false, false);
            request16.QueryStringParameters.Add("qry", "goog", false, false);
            request16.QueryStringParameters.Add("cp", "0", false, false);
            request16.QueryStringParameters.Add("cvid", "DC7BE9FB0FBE4E39A3D23C75EA5FDACC", false, false);
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("https://www.bing.com/AS/Suggestions");
            request17.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            request17.QueryStringParameters.Add("pt", "page.serp", false, false);
            request17.QueryStringParameters.Add("bq", "nUEVO", false, false);
            request17.QueryStringParameters.Add("mkt", "es-cr", false, false);
            request17.QueryStringParameters.Add("qry", "googl", false, false);
            request17.QueryStringParameters.Add("cp", "0", false, false);
            request17.QueryStringParameters.Add("cvid", "DC7BE9FB0FBE4E39A3D23C75EA5FDACC", false, false);
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("https://www.bing.com/AS/Suggestions");
            request18.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            request18.QueryStringParameters.Add("pt", "page.serp", false, false);
            request18.QueryStringParameters.Add("bq", "nUEVO", false, false);
            request18.QueryStringParameters.Add("mkt", "es-cr", false, false);
            request18.QueryStringParameters.Add("qry", "google", false, false);
            request18.QueryStringParameters.Add("cp", "0", false, false);
            request18.QueryStringParameters.Add("cvid", "DC7BE9FB0FBE4E39A3D23C75EA5FDACC", false, false);
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("https://www.bing.com/fd/ls/lsp.aspx");
            request19.Method = "POST";
            request19.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            StringHttpBody request19Body = new StringHttpBody();
            request19Body.ContentType = "text/xml";
            request19Body.InsertByteOrderMark = false;
            request19Body.BodyString = "<ClientInstRequest><Events><E><T>Event.ClientInst</T><IG>DC7BE9FB0FBE4E39A3D23C75" +
                "EA5FDACC</IG><TS>1519827962201</TS><D><![CDATA[[{\"T\":\"CI.BoxModel\",\"FID\":\"CI\",\"N" +
                "ame\":\"v2.8\",\"SV\":\"4\",\"P\":{\"C\":16,\"N\":2,\"I\":\"2kh\",\"S\":\"C+K+MT+U\",\"M\":\"V+L+M+MT+E+" +
                "N+C+K+BD\",\"T\":8580,\"K\":\"2ou+5pt+612+AS%2FSuggestions+66n+69e+6ce+6ex+5q3+keydown" +
                "+keypress+66s+6ab+6j7\",\"F\":1},\"L\":\"@1l/o/INPUT#sb_form_q//3c/j/dw/u/4/K/-1+611/p" +
                "/DIV#ajaxStyles//0/0/w9/0/1/MT/-1+64y/q/UL#sa_ul//2s/1i/fk/6o/6/MT/2+6ly/q///0/0" +
                "/0/0/0/R/\",\"M\":\"jo+1v3+jt+6m1+12+0+0+1+0+i6+1\",\"N\":\"2or/u//@6/ls%2Flsp.aspx/@11/" +
                "36/@8/@1d/-1/@1d/2ro/2rw/2ry+36p/v//www2.bing.com/ipv6test%2Ftest/@n/9u/@8/-1/-1" +
                "/-1/-1/-1/3gk+5ps/w//@6/AutoSug/@n/a7/@8/@1e/-1/@1e/5pu/5zh/5zz+60z/x//@6/@1g/@1" +
                "1/3d/@8/@1f/-1/@1f/@1f/64a/64d+66m/y//@6/@1g/@11/4n/@8/@1h/-1/@1h/@1h/6b8/6b9+69" +
                "c/z//@6/@1g/@11/6g/@8/@1i/-1/@1i/@1i/6fq/6fs+6cc/10//@6/@1g/@11/3c/@8/@1j/-1/@1j" +
                "/@1j/6fn/6fp+6ev/11//@6/@1g/@11/3s/@8/@1k/-1/@1k/@1k/6in/6io\",\"C\":\"4l3//////1p/+" +
                "4mn/2////8p/1f/+4t3/o////8l/15/+4yg//pointerdown//0//z/1+500//@1c//-1/86/v/+50f/" +
                "////7o/q/+50n/////7c/n/+50v/////6y/k/+514/2////6l/i/+51b/////66/g/+51j/////5p/f/" +
                "+51r/////58//+51z/////4m//+527/////40//+52f/////3h//+52n/////2y//+52w/////2f//+5" +
                "33/////20//+53b/////1n//+53j/////1c//+53z/////y//+54f/////n//+55r/////d/b/+57b//" +
                "pointerup//0//9/0\",\"K\":\"@1l/o/@1m/0+5q7/o/@1n/0+5yz/o/@1m/0+5z0/o/@1n/0+643/o/@1" +
                "m/0+644/o/@1n/0+@1o/o/@1m/0+@1o/o/@1n/0+@1p/o/@1m/0+@1p/o/@1n/0+6e3/o/@1m/0+6e4/" +
                "o/@1n/0+@1q/o/@1m/0+@1q/o/@1n/0\"}]]]></D></E></Events><STS>1519827962201</STS></" +
                "ClientInstRequest>";
            request19.Body = request19Body;
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest("https://www.bing.com/search");
            request20.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            request20.QueryStringParameters.Add("q", "GOOGLE", false, false);
            request20.QueryStringParameters.Add("qs", this.Context["$HIDDEN1.qs"].ToString(), false, false);
            request20.QueryStringParameters.Add("form", this.Context["$HIDDEN1.form"].ToString(), false, false);
            request20.QueryStringParameters.Add("sp", "-1", false, false);
            request20.QueryStringParameters.Add("pq", "google", false, false);
            request20.QueryStringParameters.Add("sc", "8-6", false, false);
            request20.QueryStringParameters.Add("sk", this.Context["$HIDDEN1.sk"].ToString(), false, false);
            request20.QueryStringParameters.Add("cvid", "DC7BE9FB0FBE4E39A3D23C75EA5FDACC", false, false);
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest("https://www.bing.com/fd/ls/l");
            request21.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            request21.QueryStringParameters.Add("IG", "011735760C964CE5AA98DB371A6E67FC", false, false);
            request21.QueryStringParameters.Add("Type", "Event.CPT", false, false);
            request21.QueryStringParameters.Add("DATA", "{%22pp%22:{%22S%22:%22L%22,%22FC%22:18,%22BC%22:18,%22SE%22:-1,%22TC%22:-1,%22H%2" +
                    "2:33,%22BP%22:119,%22CT%22:125,%22IL%22:1},%22ad%22:[162,81,1161,782,1161,1558,0" +
                    "]}", false, false);
            request21.QueryStringParameters.Add("P", "SERP", false, false);
            request21.QueryStringParameters.Add("DA", "CH01", false, false);
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest("https://www.bing.com/fd/ls/lsp.aspx");
            request22.ThinkTime = 2;
            request22.Method = "POST";
            request22.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            request22.QueryStringParameters.Add("", "", false, false);
            StringHttpBody request22Body = new StringHttpBody();
            request22Body.ContentType = "text/xml";
            request22Body.InsertByteOrderMark = false;
            request22Body.BodyString = @"<ClientInstRequest><Events><E><T>Event.ClientInst</T><IG>011735760C964CE5AA98DB371A6E67FC</IG><TS>1519827963081</TS><D><![CDATA[{id:1252,P:""7:3,5:3,15:nz,14:ls,13:ls,12:ls,11:4m,4:3,3:3,2:3,17:o4,16:o4,24:m1,8:4m,10:ip,9:4m,19:iq,18:iq"",S:""nav:0"",v:1.1,T:""CI.Perf"",FID:""CI"",Name:""PerfV2""}]]></D></E></Events><STS>1519827963081</STS></ClientInstRequest>";
            request22.Body = request22Body;
            yield return request22;
            request22 = null;

            WebTestRequest request23 = new WebTestRequest("https://www.bing.com/fd/ls/lsp.aspx");
            request23.Method = "POST";
            request23.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            StringHttpBody request23Body = new StringHttpBody();
            request23Body.ContentType = "text/xml";
            request23Body.InsertByteOrderMark = false;
            request23Body.BodyString = "<ClientInstRequest><Events><E><T>Event.ClientInst</T><IG>011735760C964CE5AA98DB37" +
                "1A6E67FC</IG><TS>1519827965088</TS><D><![CDATA[[{\"T\":\"CI.BoxModel\",\"FID\":\"CI\",\"N" +
                "ame\":\"v2.8\",\"SV\":\"4\",\"P\":{\"C\":22,\"N\":1,\"I\":\"t7\",\"S\":\"T+C+BD+U\",\"M\":\"V+L+M+MT+E+N" +
                "+C+K+BD\",\"T\":2877,\"K\":\"SPAN.ftrB+LI.b_algo+LI.b_ans+17a+SERP,5317.1,Ads+LI.b_adL" +
                "astChild+SERP,5319.1,Ads+img+https+www.bing.com+Framework+script+Identity%2520Bl" +
                "ue%24BlueIdentityDropdownBootStrap_Redirect+Identity%2520Blue%24BlueIdentityHead" +
                "er+LanguageSwitch+SegmentFilters%2520Blue%24GenericDropDownModernCalendar+WebRes" +
                "ult%2520Blue%24WebResultToolboxBlue+Web%2520SerpKeyboardNavigation_SelectorHeade" +
                "rPlusAlgo+Web%2520SerpKeyboardNavigation+25t+27i+pointermove\",\"F\":1},\"V\":\"la/0/0" +
                "/wq/lq/w9/3b/1/d/visible/default+lo//////@3////\",\"L\":\"lb/0/NAV.b_scopebar/SERP,5" +
                "016.1/2s/27/th/13/2/T/-1+lb/1/H1.b_logo//1m/g/s/10/4/T/-1+lb/2/DIV.b_searchboxFo" +
                "rm//2s/e/fk/14/3/T/-1+lb/3/DIV#id_h/SERP,5021.1/0/0/0/0/2/T/2+lq/4/SPAN.sb_count" +
                "//3c/3o/3k/u/3/T/-1+lq/5/@0/SERP,5247.1/6w/3o/2q/u/3/T/-1+lq/6/@0/SERP,5255.1/9n" +
                "/3o/3i/u/3/T/-1+lq/7/@0/SERP,5259.1/d5/3o/2e/u/3/T/-1+lq/8/LI.b_ad/@4/2s/4i/fk/2" +
                "9/3/T/-1+lq/9/@1/SERP,5096.1/2s/6r/fk/28/3/T/-1+lq/a/@1/SERP,5107.1/2s/91/fk/2t/" +
                "3/T/-1+lq/b/@1/SERP,5117.1/2s/bw/fk/28/3/T/-1+lq/c/@1/SERP,5130.1/2s/e6/fk/2p/3/" +
                "T/-1+lq/d/@1/SERP,5143.1/2s/gx/fk/28/3/T/-1+lq/e/@1/SERP,5158.1/2s/j7/fk/2p/3/T/" +
                "-1+lq/f/@1/SERP,5171.1/2s/ly/fk/2p/3/T/-1+lq/g/@1/SERP,5183.1/2s/op/fk/2p/3/T/-1" +
                "+lq/h/@1/SERP,5195.1/2s/rg/fk/28/3/T/-1+lq/i/@1/SERP,5208.1/2s/tq/fk/2p/3/T/-1+l" +
                "q/j/LI.b_ad b_adBottom/@6/2s/wh/fk/2a/3/T/-1+lq/k/@2/SERP,5298.1/2s/yr/fk/55/3/T" +
                "/-1+lq/l/LI.b_pag/SERP,5333.1/2s/13y/fk/2q/3/T/-1+lq/m/@2/SERP,5323.1/jg/4i/ao/5" +
                "l/3/T/-1+lq/n/FOOTER#b_footer/SERP,5034.1/0/@3/w9/1c/1/T/-1+lb/o/IMG//1m/g/jb/1q" +
                "/5/T/-1+lq/p/@5/@4/3c/4s/eg/1q/5/T/-1+lq/q/@5/@6/3c/wt/eg/1q/5/T/-1+27r/3///r0/a" +
                "/45/1e//R/\",\"M\":\"iq+zp+m1+27t+n+0+0+0+0+bb+1\",\"N\":\"-1/0///document//o4//3/-1/3/4" +
                "m/4m/ip+iq/1/o/@9/simg%2FSharedSpriteDesktopTwoToneLogoTealSpy_0817.png/@7/0/@8/" +
                "iq/-1/iq/iq/iq/iq+iq/2//storage.live.com/profilephoto%3AUserTileStatic%2Fp/@7/4p" +
                "/@8/-1/-1/-1/-1/-1/ng+oa/3//@9/cpt/@7/1p/@8/ob/-1/ob/ob/-1/q0+oc/4//@9/ls%2Flsp." +
                "aspx/xmlhttprequest/3f/@8/oh/-1/oh/ra/rq/rr+oe/5//@9/BingCore.Bundle/@b/1/@8/og/" +
                "-1/og/og/og/og+s3/6//@9/@a/@7/3/@8/s6/-1/s6/s6/s6/s6+s7/7//@9/@c/@7/2/@8/sa/-1/s" +
                "a/sa/sa/sa+sb/8//@9/@d/@7/3/@8/se/-1/se/se/se/se+sg/9//@9/@e/@7/5/@8/sj/-1/sj/sj" +
                "/sj/sm+sn/a//@9/@f/@7/3/@8/sq/-1/sq/sq/sq/sq+sr/b//@9/@g/@7/2/@8/st/-1/st/st/st/" +
                "st+su/c//@9/@h/@7/2/@8/sw/-1/sw/sw/sw/sw+sx/d//@9/@i/@7/1/@8/sz/-1/sz/sz/sz/sz+t" +
                "0/e//@9/@a/@b/1/@8/t1/-1/t1/t1/t1/t2+ti/f//@9/@c/@b/1/@8/tk/-1/tk/tk/tk/tk+tm/g/" +
                "/@9/@d/@b/1/@8/tn/-1/tn/tn/tn/to+tp/h//@9/@e/@b/1/@8/tr/-1/tr/tr/tr/tr+tw/i//@9/" +
                "@f/@b/1/@8/tx/-1/tx/tx/tx/ty+u3/j//@9/@g/@b/1/@8/u5/-1/u5/u5/u5/u5+ui/k//@9/@h/@" +
                "b/1/@8/uk/-1/uk/uk/uk/uk+uo/l//@9/@i/@b/1/@8/uq/-1/uq/uq/uq/uq+25r/m//@9/ls%2FGL" +
                "inkPing.aspx/@7/1t/@8/@j/-1/@j/@j/@k/27l\",\"C\":\"zp//@l/mouse/-1/0/4g/0+zx/////g/4" +
                "l/+105/////15/4r/+10d/////1o/4w/+10l/////26/50/+10t/8////2t/5b/+111/////38/5h/+1" +
                "19/p////3j/5m/+11h/////3t/5s/+11p/////43/5z/+125/////4e/68/+12t/8////4l/6i/+13x/" +
                "9/////6t/+14l/////4j/73/+159/////4f/7f/+16t/////46/7o/+17p/////3x/7u/+18l/////3t" +
                "/85/+1cd/////3y/7w/+1il/////42/8d/+1it/////45/8n/+1j1/////49/90/+1ji/a////4e/9l/" +
                "+1js/////4j/9w/+1k1/////4n/a6/+1k5/////4p/ag/+1kl/////4u/ar/+1pa/////4r/ag/+1qd/" +
                "////4k/a7/+1v1/////4d/9z/+25q//pointerdown//0//9x/1+27h//pointerup/////0+@k//cli" +
                "ck/////\",\"BD\":\"zp/@l/1519827963\"}]]]></D></E></Events><STS>1519827965088</STS></" +
                "ClientInstRequest>";
            request23.Body = request23Body;
            yield return request23;
            request23 = null;

            WebTestRequest request24 = new WebTestRequest("http://www.google.com/intl/jw/");
            request24.ExpectedResponseUrl = "https://www.google.com/?hl=jw&gws_rd=ssl";
            request24.Headers.Add(new WebTestRequestHeader("Referer", "https://www.bing.com/"));
            WebTestRequest request24Dependent1 = new WebTestRequest("https://www.google.com/gen_204");
            request24Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/?hl=jw&gws_rd=ssl"));
            request24Dependent1.QueryStringParameters.Add("s", "webaft", false, false);
            request24Dependent1.QueryStringParameters.Add("atyp", this.Context["QueryStringParam289.atyp"].ToString(), false, false);
            request24Dependent1.QueryStringParameters.Add("ei", this.Context["$HIDDEN1.ei"].ToString(), false, false);
            request24Dependent1.QueryStringParameters.Add("rt", "wsrt.753,aft.336,prt.336", false, false);
            request24.DependentRequests.Add(request24Dependent1);
            ExtractHiddenFields extractionRule5 = new ExtractHiddenFields();
            extractionRule5.Required = true;
            extractionRule5.HtmlDecode = true;
            extractionRule5.ContextParameterName = "1";
            request24.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule5.Extract);
            ExtractText extractionRule6 = new ExtractText();
            extractionRule6.StartsWith = "&atyp=";
            extractionRule6.EndsWith = "&";
            extractionRule6.Index = 0;
            extractionRule6.IgnoreCase = false;
            extractionRule6.UseRegularExpression = false;
            extractionRule6.HtmlDecode = true;
            extractionRule6.Required = false;
            extractionRule6.ContextParameterName = "QueryStringParam289.atyp";
            request24.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule6.Extract);
            ExtractText extractionRule7 = new ExtractText();
            extractionRule7.StartsWith = "&atyp=";
            extractionRule7.EndsWith = "&";
            extractionRule7.Index = 0;
            extractionRule7.IgnoreCase = false;
            extractionRule7.UseRegularExpression = false;
            extractionRule7.HtmlDecode = true;
            extractionRule7.Required = false;
            extractionRule7.ContextParameterName = "QueryStringParam318.atyp";
            request24.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule7.Extract);
            yield return request24;
            request24 = null;

            WebTestRequest request25 = new WebTestRequest("https://www.google.com/xjs/_/js/k=xjs.s.en.lyr4rn8yglg.O/m=sx,sb,cdos,cr,elog,hsm" +
                    ",jsa,r,d,csi/am=wCLkdEEAyP8JgogEKwgsQIpgGBA/rt=j/d=1/t=zcms/rs=ACT90oE9xg5JXNopc" +
                    "AZtZPV-ufIRZ3jPZA");
            request25.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/?hl=jw&gws_rd=ssl"));
            yield return request25;
            request25 = null;

            WebTestRequest request26 = new WebTestRequest("https://www.gstatic.com/og/_/js/k=og.og2.en_US.PhjXuBK65wA.O/rt=j/m=def/exm=in,fo" +
                    "t/d=1/ed=1/rs=AA2YrTvynzQW2hx1c545H7wM3PtueoFk7Q");
            request26.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/?hl=jw&gws_rd=ssl"));
            yield return request26;
            request26 = null;

            WebTestRequest request27 = new WebTestRequest("https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.81qcNVAdPP0.O/m=gapi" +
                    "_iframes,googleapis_client,plusone/rt=j/sv=1/d=1/ed=1/am=AAE/rs=AHpOoo-rnjHqcvRA" +
                    "lxtG-9gMfTrV90boIA/cb=gapi.loaded_0");
            request27.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/?hl=jw&gws_rd=ssl"));
            yield return request27;
            request27 = null;

            WebTestRequest request28 = new WebTestRequest("https://www.google.com/xjs/_/js/k=xjs.s.en.zlbS1JZBH0k.O/m=aa,abd,async,dvl,foot," +
                    "fpe,ipv6,lu,m,mu,sf,sonic,d3l,WgDvvc/am=wCLkdEEAyP8JgogEKwgsQIpgGBA/exm=sx,sb,cd" +
                    "os,cr,elog,hsm,jsa,r,d,csi/rt=j/d=1/ed=1/t=zcms/rs=ACT90oHKFlkvRuECYYNZZ5H6gPwKO" +
                    "nB24g");
            request28.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/?hl=jw&gws_rd=ssl"));
            request28.QueryStringParameters.Add("xjs", "s1", false, false);
            yield return request28;
            request28 = null;

            WebTestRequest request29 = new WebTestRequest("https://www.google.com/gen_204");
            request29.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/?hl=jw&gws_rd=ssl"));
            request29.QueryStringParameters.Add("atyp", this.Context["QueryStringParam318.atyp"].ToString(), false, false);
            request29.QueryStringParameters.Add("ei", this.Context["$HIDDEN1.ei"].ToString(), false, false);
            request29.QueryStringParameters.Add("s", "webhp", false, false);
            request29.QueryStringParameters.Add("imc", "2", false, false);
            request29.QueryStringParameters.Add("imn", "2", false, false);
            request29.QueryStringParameters.Add("imp", "0", false, false);
            request29.QueryStringParameters.Add("adh", "", false, false);
            request29.QueryStringParameters.Add("ima", "1", false, false);
            request29.QueryStringParameters.Add("ime", "0", false, false);
            request29.QueryStringParameters.Add("rt", "aft.336,dcl.342,iml.336,ol.377,prt.336,xjs.1108,xjsee.1108,xjses.979,xjsls.471,ws" +
                    "rt.753,cst.0,dnst.0,rqst.101,rspt.100,rqstt.703,unt.703,cstt.703,dit.1095", false, false);
            request29.QueryStringParameters.Add("zx", "1519827966955", false, false);
            yield return request29;
            request29 = null;

            WebTestRequest request30 = new WebTestRequest("https://adservice.google.com/adsid/google/ui");
            request30.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/?hl=jw&gws_rd=ssl"));
            yield return request30;
            request30 = null;

            WebTestRequest request31 = new WebTestRequest("https://www.google.com/xjs/_/js/k=xjs.s.en.zlbS1JZBH0k.O/m=RMhBfe/am=wCLkdEEAyP8J" +
                    "gogEKwgsQIpgGBA/exm=sx,sb,cdos,cr,elog,hsm,jsa,r,d,csi,aa,abd,async,dvl,foot,fpe" +
                    ",ipv6,lu,m,mu,sf,sonic,d3l,WgDvvc/rt=j/d=1/ed=1/t=zcms/rs=ACT90oHKFlkvRuECYYNZZ5" +
                    "H6gPwKOnB24g");
            request31.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/?hl=jw&gws_rd=ssl"));
            yield return request31;
            request31 = null;

            WebTestRequest request32 = new WebTestRequest("https://www.google.co.cr/domainless/read");
            request32.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/?hl=jw&gws_rd=ssl"));
            request32.QueryStringParameters.Add("igu", "1", false, false);
            yield return request32;
            request32 = null;

            WebTestRequest request33 = new WebTestRequest("https://www.google.com/domainless/write");
            request33.ThinkTime = 8;
            request33.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/?hl=jw&gws_rd=ssl"));
            request33.QueryStringParameters.Add("igu", "1", false, false);
            request33.QueryStringParameters.Add("data", "", false, false);
            request33.QueryStringParameters.Add("xsrf", "ALAmJdF_5HhIlEd2gZ3FZRyNX5RNvPmfDg:1519828073755", false, false);
            yield return request33;
            request33 = null;

            WebTestRequest request34 = new WebTestRequest("https://www.google.com/search");
            request34.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/?hl=jw&gws_rd=ssl"));
            request34.QueryStringParameters.Add("hl", this.Context["$HIDDEN1.hl"].ToString(), false, false);
            request34.QueryStringParameters.Add("source", this.Context["$HIDDEN1.source"].ToString(), false, false);
            request34.QueryStringParameters.Add("ei", this.Context["$HIDDEN1.ei"].ToString(), false, false);
            request34.QueryStringParameters.Add("q", "Busqueda", false, false);
            request34.QueryStringParameters.Add("oq", "Busqueda", false, false);
            request34.QueryStringParameters.Add("gs_l", "psy-ab.3...1406.7149.0.8566.0.0.0.0.0.0.0.0..0.0....0...1c.1.64.psy-ab..0.0.0...." +
                    "0.swaUHzo-oTc", false, false);
            yield return request34;
            request34 = null;

            WebTestRequest request35 = new WebTestRequest("https://www.google.com/gen_204");
            request35.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/search?hl=jw&source=hp&ei=abyWWoq6LMmn5gKR7o_QDg&q=Busqued" +
                        "a&oq=Busqueda&gs_l=psy-ab.3...1406.7149.0.8566.0.0.0.0.0.0.0.0..0.0....0...1c.1." +
                        "64.psy-ab..0.0.0....0.swaUHzo-oTc"));
            request35.QueryStringParameters.Add("s", "webaft", false, false);
            request35.QueryStringParameters.Add("atyp", "csi", false, false);
            request35.QueryStringParameters.Add("ei", "c7yWWteGI6bv5gKesYe4CA", false, false);
            request35.QueryStringParameters.Add("rt", "wsrt.275,aft.364,prt.364,sct.302", false, false);
            yield return request35;
            request35 = null;

            WebTestRequest request36 = new WebTestRequest("https://www.google.com/xjs/_/js/k=xjs.s.en.lyr4rn8yglg.O/m=sx,sb,cdos,cr,elog,hsm" +
                    ",jsa,r,d,csi/am=wCLkdEEAyP8JgogEKwgsQIpgGBA/rt=j/d=1/t=zcms/rs=ACT90oE9xg5JXNopc" +
                    "AZtZPV-ufIRZ3jPZA");
            request36.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/search?hl=jw&source=hp&ei=abyWWoq6LMmn5gKR7o_QDg&q=Busqued" +
                        "a&oq=Busqueda&gs_l=psy-ab.3...1406.7149.0.8566.0.0.0.0.0.0.0.0..0.0....0...1c.1." +
                        "64.psy-ab..0.0.0....0.swaUHzo-oTc"));
            yield return request36;
            request36 = null;

            WebTestRequest request37 = new WebTestRequest(@"https://www.google.com/xjs/_/js/k=xjs.s.en.zlbS1JZBH0k.O/m=aa,abd,async,dvl,foot,fpe,ipv6,lu,m,mu,sf,sonic,tl,vs,d3l,tnv,mrn,me,atn,WgDvvc/am=wCLkdEEAyP8JgogEKwgsQIpgGBA/exm=sx,sb,cdos,cr,elog,hsm,jsa,r,d,csi/rt=j/d=1/ed=1/t=zcms/rs=ACT90oHKFlkvRuECYYNZZ5H6gPwKOnB24g");
            request37.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/search?hl=jw&source=hp&ei=abyWWoq6LMmn5gKR7o_QDg&q=Busqued" +
                        "a&oq=Busqueda&gs_l=psy-ab.3...1406.7149.0.8566.0.0.0.0.0.0.0.0..0.0....0...1c.1." +
                        "64.psy-ab..0.0.0....0.swaUHzo-oTc"));
            request37.QueryStringParameters.Add("xjs", "s1", false, false);
            yield return request37;
            request37 = null;

            WebTestRequest request38 = new WebTestRequest("https://www.google.com/client_204");
            request38.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/search?hl=jw&source=hp&ei=abyWWoq6LMmn5gKR7o_QDg&q=Busqued" +
                        "a&oq=Busqueda&gs_l=psy-ab.3...1406.7149.0.8566.0.0.0.0.0.0.0.0..0.0....0...1c.1." +
                        "64.psy-ab..0.0.0....0.swaUHzo-oTc"));
            request38.QueryStringParameters.Add("", "", false, false);
            request38.QueryStringParameters.Add("atyp", "i", false, false);
            request38.QueryStringParameters.Add("biw", "1178", false, false);
            request38.QueryStringParameters.Add("bih", "782", false, false);
            request38.QueryStringParameters.Add("ei", "c7yWWteGI6bv5gKesYe4CA", false, false);
            yield return request38;
            request38 = null;

            WebTestRequest request39 = new WebTestRequest("https://www.google.com/gen_204");
            request39.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/search?hl=jw&source=hp&ei=abyWWoq6LMmn5gKR7o_QDg&q=Busqued" +
                        "a&oq=Busqueda&gs_l=psy-ab.3...1406.7149.0.8566.0.0.0.0.0.0.0.0..0.0....0...1c.1." +
                        "64.psy-ab..0.0.0....0.swaUHzo-oTc"));
            request39.QueryStringParameters.Add("atyp", "csi", false, false);
            request39.QueryStringParameters.Add("ei", "c7yWWteGI6bv5gKesYe4CA", false, false);
            request39.QueryStringParameters.Add("s", "web", false, false);
            request39.QueryStringParameters.Add("imc", "7", false, false);
            request39.QueryStringParameters.Add("imn", "7", false, false);
            request39.QueryStringParameters.Add("imp", "0", false, false);
            request39.QueryStringParameters.Add("adh", "", false, false);
            request39.QueryStringParameters.Add("rt", "aft.364,dcl.401,iml.364,ol.461,prt.364,xjs.689,xjsee.689,xjses.586,xjsls.512,sct." +
                    "302,wsrt.275,cst.0,dnst.0,rqst.471,rspt.470,rqstt.167,unt.2,cstt.2,dit.676", false, false);
            request39.QueryStringParameters.Add("zx", "1519827976490", false, false);
            yield return request39;
            request39 = null;

            WebTestRequest request40 = new WebTestRequest("https://www.gstatic.com/og/_/js/k=og.og2.en_US.PhjXuBK65wA.O/rt=j/m=def/exm=in,fo" +
                    "t/d=1/ed=1/rs=AA2YrTvynzQW2hx1c545H7wM3PtueoFk7Q");
            request40.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/search?hl=jw&source=hp&ei=abyWWoq6LMmn5gKR7o_QDg&q=Busqued" +
                        "a&oq=Busqueda&gs_l=psy-ab.3...1406.7149.0.8566.0.0.0.0.0.0.0.0..0.0....0...1c.1." +
                        "64.psy-ab..0.0.0....0.swaUHzo-oTc"));
            yield return request40;
            request40 = null;

            WebTestRequest request41 = new WebTestRequest("https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.81qcNVAdPP0.O/m=gapi" +
                    "_iframes,googleapis_client,plusone/rt=j/sv=1/d=1/ed=1/am=AAE/rs=AHpOoo-rnjHqcvRA" +
                    "lxtG-9gMfTrV90boIA/cb=gapi.loaded_0");
            request41.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/search?hl=jw&source=hp&ei=abyWWoq6LMmn5gKR7o_QDg&q=Busqued" +
                        "a&oq=Busqueda&gs_l=psy-ab.3...1406.7149.0.8566.0.0.0.0.0.0.0.0..0.0....0...1c.1." +
                        "64.psy-ab..0.0.0....0.swaUHzo-oTc"));
            yield return request41;
            request41 = null;

            WebTestRequest request42 = new WebTestRequest("https://adservice.google.com/adsid/google/ui");
            request42.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/search?hl=jw&source=hp&ei=abyWWoq6LMmn5gKR7o_QDg&q=Busqued" +
                        "a&oq=Busqueda&gs_l=psy-ab.3...1406.7149.0.8566.0.0.0.0.0.0.0.0..0.0....0...1c.1." +
                        "64.psy-ab..0.0.0....0.swaUHzo-oTc"));
            yield return request42;
            request42 = null;

            WebTestRequest request43 = new WebTestRequest(@"https://www.google.com/xjs/_/js/k=xjs.s.en.zlbS1JZBH0k.O/m=RMhBfe/am=wCLkdEEAyP8JgogEKwgsQIpgGBA/exm=sx,sb,cdos,cr,elog,hsm,jsa,r,d,csi,aa,abd,async,dvl,foot,fpe,ipv6,lu,m,mu,sf,sonic,tl,vs,d3l,tnv,mrn,me,atn,WgDvvc/rt=j/d=1/ed=1/t=zcms/rs=ACT90oHKFlkvRuECYYNZZ5H6gPwKOnB24g");
            request43.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/search?hl=jw&source=hp&ei=abyWWoq6LMmn5gKR7o_QDg&q=Busqued" +
                        "a&oq=Busqueda&gs_l=psy-ab.3...1406.7149.0.8566.0.0.0.0.0.0.0.0..0.0....0...1c.1." +
                        "64.psy-ab..0.0.0....0.swaUHzo-oTc"));
            yield return request43;
            request43 = null;
        }
    }
}
